UPDATE `test`.`remind_word` SET `id`='85', `tag`='hecto', `content`='表示“百，许多”', `connect`='他成为cto每天要喝许多饮料,多达百种' WHERE (`id`='85');
UPDATE `test`.`remind_word` SET `id`='86', `tag`='hemi', `content`='表示“半”', `connect`='他把一半的米当成饮料, 喝了进去' WHERE (`id`='86');
UPDATE `test`.`remind_word` SET `id`='87', `tag`='hepta', `content`='表示“七”', `connect`='七夕他陪TA,一起' WHERE (`id`='87');
UPDATE `test`.`remind_word` SET `id`='88', `tag`='hexa', `content`='表示“六”', `connect`='吃了河虾,手固定成6的姿势,中毒很深' WHERE (`id`='88');
UPDATE `test`.`remind_word` SET `id`='89', `tag`='holo', `content`='表示“全部”', `connect`='全部的红楼都不能居住,流落街头' WHERE (`id`='89');
UPDATE `test`.`remind_word` SET `id`='90', `tag`='intra', `content`='表示“在内，内部”', `connect`='4个太能能和提子,在内部绕一起,风吹不倒' WHERE (`id`='90');
UPDATE `test`.`remind_word` SET `id`='91', `tag`='iso', `content`='表示“等，同”', `connect`='iso的组织对所有人都是同等的,不能偏袒' WHERE (`id`='91');
UPDATE `test`.`remind_word` SET `id`='92', `tag`='kilo', `content`='表示“一千”', `connect`='把一千个游泳圈都放弃了, 后来被抓kill了' WHERE (`id`='92');
UPDATE `test`.`remind_word` SET `id`='93', `tag`='meta', `content`='表示“超过，改变”', `connect`='给我多少钱都不能改变我和他的关系,已经超过了钱的友情' WHERE (`id`='93');
UPDATE `test`.`remind_word` SET `id`='94', `tag`='milli', `content`='表示“千，千分之一”', `connect`='从一堆米粒中找出一千粒,老是多了一个1,要从数' WHERE (`id`='94');
UPDATE `test`.`remind_word` SET `id`='95', `tag`='ob', `content`='表示“逆，倒，加强意义”', `connect`='欧巴你不要倒下去, 不是甲醛,是药' WHERE (`id`='95');
UPDATE `test`.`remind_word` SET `id`='96', `tag`='octa', `content`='表示“八”（亦作octo）', `connect`='八个提子摆成8字形' WHERE (`id`='96');
