UPDATE `test`.`remind_word` SET `tag` = 'penta', `content` = '表示“五”', `connect` = '一个有五只手脚的人, 专门拿出一只手碰瓷,' WHERE `id` = 97;
UPDATE `test`.`remind_word` SET `tag` = 'quadri-, quadru', `content` = '表示“四”', `connect` = '蛆虫在奥迪车上被日光晒死了' WHERE `id` = 98;
UPDATE `test`.`remind_word` SET `tag` = 'quasi', `content` = '表示“类似，准”', `connect` = '甜甜圈从天上掉下,砸准他,砸死了, 好几个人搬,搬得类似' WHERE `id` = 99;
UPDATE `test`.`remind_word` SET `tag` = 'semi', `content` = '表示“半”', `connect` = '他半只眼睛色眯眯的盯着人看' WHERE `id` = 100;
UPDATE `test`.`remind_word` SET `tag` = 'sept,septi', `content` = '表示“七”', `connect` = '涩涩的葡萄,怎么吃,一定是七月份的,八月才熟' WHERE `id` = 101;
UPDATE `test`.`remind_word` SET `tag` = 'sex', `content` = '表示“六”', `connect` = '这么性感让人流口水' WHERE `id` = 102;
UPDATE `test`.`remind_word` SET `tag` = 'step', `content` = '表示“后，继或前夫（妻）所生”', `connect` = '步伐再不快,寄生虫要从后面追上你了' WHERE `id` = 103;
UPDATE `test`.`remind_word` SET `tag` = 'stereo', `content` = '表示“立体”', `connect` = '带着很厚的手套的人,不能把梳子很立体的摆成游泳圈的样子' WHERE `id` = 104;
UPDATE `test`.`remind_word` SET `tag` = 'supra', `content` = '表示“超…  ”', `connect` = '切换平壤为超级国家' WHERE `id` = 105;
UPDATE `test`.`remind_word` SET `tag` = 'tetra', `content` = '表示“四”', `connect` = 'quadri,quadru,天鹅被土壤上面的小草绊倒了,直接死了' WHERE `id` = 106;
UPDATE `test`.`remind_word` SET `tag` = 'tri', `content` = '表示“三”', `connect` = '泰山上同时升起了3个太阳' WHERE `id` = 107;
UPDATE `test`.`remind_word` SET `tag` = 'twi', `content` = '表示“二，两”', `connect` = 'Twitter一直排名为第二名' WHERE `id` = 108;
UPDATE `test`.`remind_word` SET `tag` = 'uni', `content` = '表示“一个，单一”', `connect` = '磁铁吸泥中的沙子,在沙子上面划过就形成一种一致的形状' WHERE `id` = 109;
UPDATE `test`.`remind_word` SET `tag` = 'vice', `content` = '表示“副”', `connect` = '你嗓音很动听,天生的一副好嗓音,特别是唱副歌部分,就像跳动的音符' WHERE `id` = 110;
UPDATE `test`.`remind_word` SET `tag` = 'with', `content` = '表示“向后，相反”', `connect` = '不要和你有相反意见的人说话,特别不要向后说话' WHERE `id` = 111;
UPDATE `test`.`remind_word` SET `tag` = '-ability', `content` = '表名词，“能…；性质”', `connect` = '按比例体验这辆车的性能好不好,你是中间的那个' WHERE `id` = 112;
UPDATE `test`.`remind_word` SET `tag` = '-able', `content` = '表形容词，“可…的，能…”', `connect` = '岸边的水,喝了能解渴' WHERE `id` = 113;
UPDATE `test`.`remind_word` SET `tag` = '-ably', `content` = '表副词，“能…地”', `connect` = '在岸边用路由器吸收能量,赋能给自己' WHERE `id` = 114;
UPDATE `test`.`remind_word` SET `tag` = '-aceous', `content` = '表形容词，“具有…特征的”', `connect` = '蛇喜欢吃相同特征的s状的藕丝' WHERE `id` = 115;
UPDATE `test`.`remind_word` SET `tag` = '-acious', `content` = '表形容词，“有特征的，多…的”', `connect` = '暗刺直接插在藕丝上,很有特征,能辨认出来' WHERE `id` = 116;
UPDATE `test`.`remind_word` SET `tag` = '-acity', `content` = '表名词，“有…倾向”', `connect` = '一个城市的标志是人字梯, 时间久了有倒下来的倾向' WHERE `id` = 117;
UPDATE `test`.`remind_word` SET `tag` = '-acle', `content` = '表名词，“…物品，状态”', `connect` = '爱吃辣的鹅, 把雾化,雾状的一定很好香,很好吃' WHERE `id` = 118;
UPDATE `test`.`remind_word` SET `tag` = '-acy', `content` = '表名词，“→性质，状态”', `connect` = '爱吃鱼,性子不能太急,不能直接生吃这个是一个半生不熟的状态' WHERE `id` = 119;
UPDATE `test`.`remind_word` SET `tag` = '-ad', `content` = '表名词，“…东西，状态”', `connect` = '前面奥迪在开, 后面好像出现什么问题,一个东西撞到了,原来是砖头' WHERE `id` = 120;
UPDATE `test`.`remind_word` SET `tag` = '-ade', `content` = '表名词①表示“状态，物品”②表示“个人或集体”', `connect` = '阿德的个人的物品被集体没收了, 现在身无分文的状态' WHERE `id` = 121;
UPDATE `test`.`remind_word` SET `tag` = '-age', `content` = '名词后缀①表示“状态，总称”②表示“场所，物品”③表示“费用”', `connect` = '一个年纪二十的人,装成老总,到会所,把物品都拿走,还要费用' WHERE `id` = 122;
UPDATE `test`.`remind_word` SET `tag` = '-ain', `content` = '表名词，“…人”', `connect` = '爱你这个人' WHERE `id` = 123;
UPDATE `test`.`remind_word` SET `tag` = '-aire', `content` = '表名词', `connect` = '爱惹事,出名麻烦' WHERE `id` = 124;
UPDATE `test`.`remind_word` SET `tag` = '-al', `content` = '①表形容词，“…的”②表名词，“人，物，状态”', `connect` = '阿里的任务给人感觉很忙的状态' WHERE `id` = 125;
UPDATE `test`.`remind_word` SET `tag` = '-ality', `content` = '表名词，“状态，性质”', `connect` = '案例题很会做, 都做了, 也不能改变这个现状' WHERE `id` = 126;
UPDATE `test`.`remind_word` SET `tag` = '-ally', `content` = '表副词，由al+ly 构成，“…地”', `connect` = '所有的弹弓都打到地上了' WHERE `id` = 127;
UPDATE `test`.`remind_word` SET `tag` = '-an', `content` = '表名词和形容词，“…地方  …人', `connect` = '按钮只有这个地方的人才会按正确,按错者失效' WHERE `id` = 128;
UPDATE `test`.`remind_word` SET `tag` = '-ance', `content` = '表名词，“性质，状况”', `connect` = '按钮按在厕所,一按,各种屎的形状,还带液体' WHERE `id` = 129;
UPDATE `test`.`remind_word` SET `tag` = '-ancy=ance', `content` = '表示”性质，状况”', `connect` = '一按按钮,草原烧出个爱心形状' WHERE `id` = 130;
UPDATE `test`.`remind_word` SET `tag` = '-aneity', `content` = '来自aneous，表名词，表示“性质，状态”', `connect` = '梯子的模型放在汤圆内部,做出来的形状好好看' WHERE `id` = 131;
UPDATE `test`.`remind_word` SET `tag` = '-aneors', `content` = '表形容词，表示“…有；…特征的”', `connect` = '奥尼尔还是蛇更有特征' WHERE `id` = 132;
UPDATE `test`.`remind_word` SET `tag` = '-ant', `content` = '①表形容词，“ …的”②表名词，“…人”③表名词，“…剂”', `connect` = '蚂蚁爬的那么慢真的急死人了' WHERE `id` = 133;
UPDATE `test`.`remind_word` SET `tag` = '-ar', `content` = '①表 形容词，“…的”②表名词，“人，物”', `connect` = '阿拉伯人很有名' WHERE `id` = 134;
UPDATE `test`.`remind_word` SET `tag` = '-ard', `content` = '表名词，“不好的人”', `connect` = '一个热点被一个不好的人连接过去做坏事' WHERE `id` = 135;
UPDATE `test`.`remind_word` SET `tag` = '-arian', `content` = '表形容词或名词，“…的（人）”', `connect` = '阿拉伯人在一个很高的柱子弄了个按钮,作为警报按钮,得罪了很多人' WHERE `id` = 136;
UPDATE `test`.`remind_word` SET `tag` = '-arium', `content` = '表名词，“地点，场所”', `connect` = '一群阿拉伯人喜欢集聚在有柱子的地点一起打着伞' WHERE `id` = 137;
UPDATE `test`.`remind_word` SET `tag` = '-ary', `content` = '①表形容词，“…的”②表名词，“人，场所，物”', `connect` = '一桶燃油把那个场所的人物都烧没了' WHERE `id` = 138;
UPDATE `test`.`remind_word` SET `tag` = '-ast', `content` = '表名词，“…人，物”', `connect` = '能做出奥数题的都是大人物' WHERE `id` = 139;
UPDATE `test`.`remind_word` SET `tag` = '-aster', `content` = '表名词，“不怎么样的人”', `connect` = '出奥数题的人是不怎么的人' WHERE `id` = 140;
UPDATE `test`.`remind_word` SET `tag` = '-ate', `content` = '①表动词，“做，造成”②表形容词，“具有…的”③表名词，“人或地位”', `connect` = '吃人造肉做的食品都是具有地位的人' WHERE `id` = 141;
UPDATE `test`.`remind_word` SET `tag` = '-atic', `content` = '表形容词，“有…性质的”', `connect` = '在ic芯片上放入杏子,察觉不出' WHERE `id` = 142;
UPDATE `test`.`remind_word` SET `tag` = '-ation', `content` = '表名词，“行为，过程，结果”', `connect` = '人字梯倒了,飞出一个螺丝插入狮子的喉咙这种捕杀狮子的行为,整个过程被拍成视频,结果很严重' WHERE `id` = 143;
UPDATE `test`.`remind_word` SET `tag` = '-arive', `content` = '表形容词  “有…倾向（性质）的”', `connect` = '两台太阳能只有一台能用,到达的太阳能只有一半,有被别人动过手脚的倾向' WHERE `id` = 144;
UPDATE `test`.`remind_word` SET `tag` = '-ator', `content` = '表名词，通常由ate 结尾的动词而来，“做事的人或物', `connect` = '我在与不在都要吃饭,好好做人' WHERE `id` = 145;
UPDATE `test`.`remind_word` SET `tag` = '-atory', `content` = '①表形容词，“有…性质的”②表名词，“场所，地点”', `connect` = '有一条蛇爬上了梯子,给下面的杏子讲故事,慢慢的这个地点集聚很多的杏子' WHERE `id` = 146;
UPDATE `test`.`remind_word` SET `tag` = '-cy', `content` = '表名词，也作-acy，“性质，状态”', `connect` = '草原上的人吃鱼都很心急,都还是半生不熟的状态' WHERE `id` = 147;
UPDATE `test`.`remind_word` SET `tag` = '-dom', `content` = '表名词，“状态或领域”', `connect` = '看了动漫就是吃了士力架,状态恢复,在这个领域大显身手' WHERE `id` = 148;
UPDATE `test`.`remind_word` SET `tag` = '-ee', `content` = '表名词，“被动或主动的人”', `connect` = '两只鹅打架,不管是主动被,都被人抓了,杀了吃了' WHERE `id` = 149;
UPDATE `test`.`remind_word` SET `tag` = '-eer', `content` = '表名词，”…人员”', `connect` = '鹅统领是个饲养员,拿着一颗小草统领鹅' WHERE `id` = 150;
UPDATE `test`.`remind_word` SET `tag` = '-el', `content` = '表名词，“人 或物”', `connect` = '恶龙张开大嘴,把所有的人和物都吞进去了' WHERE `id` = 151;
UPDATE `test`.`remind_word` SET `tag` = '-en', `content` = '①表动词，“变成”②表形容词，“由…制成”，通常加在名词后面③表名词，“人或物”', `connect` = '二奶被抓起来,用鞭子抽打, 被制作成人物模型,' WHERE `id` = 152;
UPDATE `test`.`remind_word` SET `tag` = '-ence', `content` = '表名词，“性质，状态”', `connect` = '二奶跑进厕所把所有有形状的东西都往外扔,堵住了门口' WHERE `id` = 153;
UPDATE `test`.`remind_word` SET `tag` = '-ency，-iency', `content` = '表名词，ence 的变体', `connect` = '二奶搬出形状的东西读在了厕所, 一发功堵在门口的东西砸到了草原' WHERE `id` = 154;
UPDATE `test`.`remind_word` SET `tag` = '-enne', `content` = '表名词，“女性”', `connect` = '二奶在照镜子, 发现镜子里面是一个女性' WHERE `id` = 155;
UPDATE `test`.`remind_word` SET `tag` = '-ent', `content` = '①表示形容词，“…的”②表名词，“…药剂”③表名词，“…人”', `connect` = '一个梳子飞出去截断了双节棍,从电线杆上面掉下来砸到人, 头破血流,要吃3服药剂才会好' WHERE `id` = 156;
UPDATE `test`.`remind_word` SET `tag` = '-eous', `content` = '表形容词，“有…的”', `connect` = '鹅肉丝有几条都是发臭的,恶臭' WHERE `id` = 157;
UPDATE `test`.`remind_word` SET `tag` = '-er', `content` = '①表名词，“…人”②表名词，“物品，机器”③表名词，“反复做”', `connect` = '有个人的耳朵挂着一个物品,物品里面是一个机器,反复在转动着' WHERE `id` = 158;
UPDATE `test`.`remind_word` SET `tag` = '-ern', `content` = '①表形容词，“…方向的”②表名词，“…场所', `connect` = '一个人耳朵插着双节棍,能朝各个方向舞动, 没到一个场所表演都很热闹' WHERE `id` = 159;
UPDATE `test`.`remind_word` SET `tag` = '-ery', `content` = '①表名词，“场所，地点”②表名词，“行为，情况”', `connect` = '耳朵发炎会传染,在一个当地要马上隔离,病人行为要控制,情况要实时汇报到中央' WHERE `id` = 160;
UPDATE `test`.`remind_word` SET `tag` = '-esque', `content` = '表形容词，“如…的”', `connect` = '西班牙的喜鹊,是如来传法,让二舅去的' WHERE `id` = 161;
UPDATE `test`.`remind_word` SET `tag` = '-ess', `content` = '表名词，“女性，雌性”', `connect` = '一只鹅和两条女性雌性蛇在一起,被蛇咬了' WHERE `id` = 162;
UPDATE `test`.`remind_word` SET `tag` = '-et', `content` = '表名词，”小东西“ 注：-let=-et 表示“小”', `connect` = '儿童都被称为小东西,什么都小' WHERE `id` = 163;
UPDATE `test`.`remind_word` SET `tag` = '-etic', `content` = '表形容词，“属于…的”', `connect` = '儿童把一个ic芯片藏在红领巾,带回家打算放在他玩具老鼠口里的鱼中' WHERE `id` = 164;
UPDATE `test`.`remind_word` SET `tag` = '-ette', `content` = '表名词，“小的东西或状态”', `connect` = '儿童掐着天鹅的脖子,把小砖块塞进天鹅的喉咙,及其残忍' WHERE `id` = 165;
UPDATE `test`.`remind_word` SET `tag` = '-ety', `content` = '表名词，“状态”', `connect` = '儿童在打弹弓, 状态相当好,百发百中的水平' WHERE `id` = 166;
UPDATE `test`.`remind_word` SET `tag` = '-faction', `content` = '表名词，“达到的状态”，由-fy 转化而来', `connect` = '他拿起帮手的动作就达到顶峰的状态,就像飞起来' WHERE `id` = 167;
UPDATE `test`.`remind_word` SET `tag` = '-fold', `content` = '表形容词或副词，“倍，双重”', `connect` = '折叠起来变成双倍' WHERE `id` = 168;
UPDATE `test`.`remind_word` SET `tag` = '-form', `content` = '表形容词，“有…形状的”', `connect` = '表单上面记录的文字奇形怪状的,各种文字' WHERE `id` = 169;
UPDATE `test`.`remind_word` SET `tag` = '-ful', `content` = '①表形容词，“有…的②表名词，“满，量”', `connect` = '浮在水面上的三角尺,油光面目' WHERE `id` = 170;
UPDATE `test`.`remind_word` SET `tag` = '-hood', `content` = '表名词，“时期，性质等”', `connect` = '厚的书本记录汉朝时期的事情,比如杏子毒人' WHERE `id` = 171;
UPDATE `test`.`remind_word` SET `tag` = '-ia', `content` = '①表名词，“某种病”②表名词，“总称，状态”', `connect` = '柱子太高,通过梯子爬上去,来躲避某种病的传染,但这个不能承受太多的人,把身体肿起来的,用砖块砸下去' WHERE `id` = 172;
UPDATE `test`.`remind_word` SET `tag` = '-ial', `content` = '表形容词，“有…的”', `connect` = '爱去阿里,因为有的是钱,而且轻松' WHERE `id` = 173;
UPDATE `test`.`remind_word` SET `tag` = '-ian', `content` = '①表名词，“某种人”②表形容词，“…国家的”', `connect` = '在柱子上面弄个按钮,某种人按下就能说出是哪个国家的' WHERE `id` = 174;
UPDATE `test`.`remind_word` SET `tag` = '-ibility', `content` = '表名词，“具备…性质的”', `connect` = '一根柱子按比例分了, 如果是巨星占比例大' WHERE `id` = 175;
UPDATE `test`.`remind_word` SET `tag` = '-ible', `content` = '形容词“能…的”', `connect` = '岸边水那种柱子当吸管, 能解渴' WHERE `id` = 176;